api/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from api import views

app_name = 'api'

router = routers.SimpleRouter()
router.register(r'stats', views.StatsViewSet)

urlpatterns = [
    url(r'bot/handle/',
        views.HandleChatMessage.as_view(),
        name='api-handle-message'),
    url(r'^', include(router.urls))
]

aussieshopper/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/',
        include('api.urls', namespace='api')),
    url('^captcha/', include('captcha.urls')),
    url(r'^',
        include('web.urls', namespace='web'))
]

urlpatterns += staticfiles_urlpatterns()

web/urls.py
from django.conf.urls import url

from web import views

app_name = 'web'

urlpatterns = [
    url(r'statistics/$',
        views.statistics,
        name='web-statistics'),

    url(r'',
        views.IndexView.as_view(),
        name='web-index')
]

api/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField, ArrayField
from django.contrib.auth.models import User


class AussieShopperModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Created At',
                                      auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Updated At',
                                      auto_now=True)

    class Meta:
        abstract = True


class LogChatMessage(AussieShopperModel):
    KIND_MSG_UNKNOWN = 'MU'
    KIND_MSG_CMD_ADD_INTEREST = 'MCAI'
    KIND_MSG_CMD_REMOVE_INTEREST = 'MCRI'
    KIND_MSG_CMD_LIST_INTEREST = 'MCLI'
    KIND_MSG_CMD_START = 'MCS'
    KIND_MSG_CMD_LATEST = 'MCL'
    KIND_MSG_CMD_HELP = 'MCH'
    KIND_MSG_CMD_RESET = 'MRES'
    KIND_MSG_CMD_CONTACT = 'MCON'
    KIND_MSG_RESPONSE = 'MR'
    MSG_KIND = [
        (KIND_MSG_UNKNOWN, 'Unknown'),
        (KIND_MSG_CMD_ADD_INTEREST, 'Add Interest'),
        (KIND_MSG_CMD_REMOVE_INTEREST, 'Remove Interest'),
        (KIND_MSG_CMD_LATEST, 'Latest Deals'),
        (KIND_MSG_CMD_LIST_INTEREST, 'List Interests'),
        (KIND_MSG_CMD_START, 'Start'),
        (KIND_MSG_CMD_HELP, 'Help'),
        (KIND_MSG_RESPONSE, 'Response'),
        (KIND_MSG_CMD_REMOVE_INTEREST, 'Reset'),
        (KIND_MSG_CMD_CONTACT, 'Contact')
    ]
    DIRECTION_INCOMING = 'I'
    DIRECTION_OUTGOING = 'O'
    MSG_DIRECTION = [
        (DIRECTION_INCOMING, 'Incoming'),
        (DIRECTION_OUTGOING, 'Outgoing')
    ]

    text = models.CharField(verbose_name='Text',
                            max_length=100)
    original_msg = JSONField(null=True)
    kind = models.CharField(verbose_name='Kind',
                            max_length=5,
                            default=KIND_MSG_UNKNOWN,
                            choices=MSG_KIND)
    fromwhom = models.CharField(verbose_name='Who sent this',
                                max_length=150,
                                default=str)
    direction = models.CharField(verbose_name='Message Direction',
                                 max_length=1,
                                 choices=MSG_DIRECTION,
                                 default=DIRECTION_INCOMING)

    class Meta:
        verbose_name = 'LogChatMessage'
        verbose_name_plural = 'LogChatMessages'

    def __str__(self):
        return '{0}'.format(self.id)


class UserProfile(AussieShopperModel):
    duser = models.OneToOneField(User,
                                 null=True,
                                 on_delete=models.SET_NULL)
    chat_id = models.IntegerField(verbose_name='Chat ID',
                                  default=0)
    telegram_user_id = models.IntegerField(verbose_name='Telegram User ID',
                                           default=0)
    last_deal_sent_id = models.IntegerField(verbose_name='Last Deal Sent',
                                            default=0)
    last_deal_checked_id = models.IntegerField(verbose_name='Last Deal Checked',
                                               default=0)
    interests = ArrayField(verbose_name='Interests',
                           base_field=models.CharField(max_length=50, blank=True),
                           default=list)

    class Meta:
        verbose_name = 'User Profile'
        verbose_name_plural = 'User Profiles'

    def __str__(self):
        return '{0} - {1}'.format(self.duser, self.chat_id)


class Deal(AussieShopperModel):
    title = models.CharField(verbose_name='Deal',
                             max_length=250)
    link = models.URLField(verbose_name='Deal URL',
                           default=str)
    raw = JSONField(null=True)
    meta = JSONField(null=True)

    class Meta:
        verbose_name = 'Deal'
        verbose_name_plural = 'Deals'

    def __str__(self):
        return '{0}'.format(self.title)


class DataStore(AussieShopperModel):
    key = models.CharField(verbose_name='Store Key',
                           max_length=50,
                           unique=True)
    data = JSONField(verbose_name='Data Store',
                     default=dict)

    class Meta:
        verbose_name = 'Data Store'
        verbose_name_plural = 'Data Stores'

    def __str__(self):
        return '{0}'.format(self.key)

web/forms.py
from django import forms

from captcha.fields import CaptchaField


class ContactMeForm(forms.Form):
    """
    Form to handle the anonymous contact form on the homepage. The form class itself
    is only used to encapsulate the data but the markup is written explicitly for now.
    """
    name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(max_length=200, required=False)
    message = forms.CharField(widget=forms.Textarea(), required=False)
    captcha = CaptchaField()

api/views.py
import logging

from django.shortcuts import get_object_or_404

from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, AllowAny

from api import models
from api import tasks
from api import serializers

logger = logging.getLogger(__name__)


class HandleChatMessage(APIView):
    http_method_names = ['post']
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        json_msg = request.data

        logger.info(json_msg)

        lcmessage = models.LogChatMessage()
        lcmessage.original_msg = request.data
        lcmessage.save()

        tasks.handle_message.delay(json_msg, lcmessage.id)

        return Response()


class StatsViewSet(viewsets.GenericViewSet):
    queryset = models.Deal.objects.all()

    def get_queryset(self):
        return models.DataStore.objects.all()

    def get_object(self):
        qs = self.get_queryset()

        return get_object_or_404(qs, key='monthly-counts')

    @action(detail=False, url_path='deal-data-monthly')
    def chart_data_monthly(self, request):

        monthly_deal_count_store = self.get_object()
        monthly_deal_count = monthly_deal_count_store.data
        deal_keys_sorted_list = sorted(monthly_deal_count.keys())

        return Response({
            'label': 'Deals By Month',
            'labels': deal_keys_sorted_list,
            'data': [monthly_deal_count[deals_key] for deals_key in deal_keys_sorted_list]
        })

web/views.py
from django.shortcuts import render
from django.views.generic import FormView
from django.urls import reverse
from django.contrib import messages

from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url

from api import tasks, models
from .forms import ContactMeForm


class IndexView(FormView):
    template_name = 'web/index.html'
    form_class = ContactMeForm

    def get_success_url(self):
        return reverse('web:web-index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cp_key = CaptchaStore.generate_key()
        context['captcha_img_url'] = captcha_image_url(cp_key)
        context['captcha_key'] = cp_key

        return context

    def form_valid(self, form):
        # contact form submitted, send the managers an email and redirect to homepage
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']

        tasks.email_managers('anonymous_contact.html', {
            'user_name': name,
            'user_email': email,
            'message': message
        })

        messages.info(self.request, "Contact email sent.")

        return super().form_valid(form)


def statistics(request):
    context = {
        'total_deals': models.Deal.objects.count(),
        'total_messages': models.LogChatMessage.objects.count()
    }

    return render(request, 'web/statistics.html', context)

web/templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} :: AussieShopper</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/darkly/bulmaswatch.min.css">
  <link rel="stylesheet" href="//cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">
  {% block extracss %}{% endblock extracss %}
  {#  <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>#}
</head>
<body>
<section class="section is-paddingless">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item">
        <img src="{% static 'images/ASlogo.png' %}" width="25" height="25" alt="AussieShopper">
      </a>
    </div>
    <div class="navbar-menu">
      <a class="navbar-item" href="{% url 'web:web-index' %}">
        Home
      </a>
      <a class="navbar-item" href="{% url 'web:web-statistics' %}">
        Statistics
      </a>
    </div>
  </nav>
</section>
{% block content %}
{% endblock %}

{% block extrajs %}{% endblock extrajs %}
{% if USE_GOOGLE_ANALYTICS %}
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-37953963-3"></script>
  <script>
    window.dataLayer = window.dataLayer || []

    function gtag () {dataLayer.push(arguments)}

    gtag('js', new Date())

    gtag('config', 'UA-37953963-3')
  </script>
{% endif %}
</body>
</html>

web/templates/web/index.html
{% extends 'web/base.html' %}
{% load render_bundle from webpack_loader %}
{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="notification is-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h1 class="title">Welcome to the Aussie Shopper Homepage.</h1>
      <h1 class="subtitle">What is it?</h1>
      <div class="content">
        <p>
          AussieShopper is a service that helps you in finding specials in the land down under. You simply need to
          provide it with a few words that describe your interests and you will receive the latest bargains straight to
          your pocket. For example, If I’m in the market for new earphones, I add that as an interest and I will get
          notified when the service finds a deal on earphones.
        </p>

        <p>
          It works by consuming the fantastic deals at OzBargain and delivers the specials to you via the
          <a href="http://telegram.org">Telegram</a> chat application. To make use of AussieShopper, search for the
          Telegram bot @AussieShopperBot or simply click on
          <a href="https://telegram.me/aussieshopperbot">https://telegram.me/aussieshopperbot</a> to add the bot
          automatically.
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-one-third">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img src="{% static "images/telegramfindbot.png" %}" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                Find the AussieShopperBot by typing <code>@AussieShopperBot</code>
              </div>
            </div>
          </div>
        </div>
      </div>

      <h1 class="subtitle">How does it work?</h1>
      <p>
        After you add the bot and send it the <code>/start</code> command, you can interact with it via the following
        commands:
      </p>
      <div class="content">
        <ul>
          <li><code>/addinterest &lt;interest&gt;</code> allows you to add a word as an interest for example <code>/addinterest
                                                                                                                   earphones</code>.
          <li><code>/removeinterest &lt;interest&gt;</code> does the opposite. <code>&lt;interest&gt;</code> can also
                                                            be
                                                            a term such as "belkin plug".
          </li>
          <li><code>/reset</code> to remove all interests.</li>
          <li><code>/latest</code> will show you the "latest" deals since you last checked or from the beginning of
                                   the
                                   day so as not to spam you with a lot of messages.
          </li>
          <li><code>/listinterest</code> lists your currently registered interests.</li>
          <li><code>/contact &lt;text&gt;</code> to send a message to the admin ex. <code>/contact I love your
                                                                                          work</code>.
          </li>
          <li><code>/help</code> will send you some help regarding the available commands.</li>
        </ul>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-one-third">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img src="{% static "images/telegraminterestssample.png" %}"
                     alt="Sample of Telegram bot interests listing">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                This screenshot shows how you will receive specials matching your interests. The message will include a
                link to the original Ozbargain page mentioning the special.
              </div>
            </div>
          </div>
        </div>
        <div class="column is-one-third">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <img src="{% static "images/telegramsampleinteraction.png" %}"
                     alt="Sample of Telegram bot general interaction">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                This screenshot shows a sample interaction with the bot. It shows functions such as adding an interest
                and
                asking to see the help message.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>

  <section class="section is-paddingless">
    <div class="container">
      <h1 class="subtitle">How much does it cost?</h1>
      <p>Pricing is hard and I created this service because I needed it. I'd like to share it as long as I can. This
         product is free for now.</p>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <h1 class="subtitle">How can I get in touch?</h1>
      <p>If you already have and use the bot, you can use the <code>/contact &lt;message&gt;</code> command and your
         message will reach me.</p>
      <p>Otherwise, you can use the form below.</p>
      <div class="columns">
        <div class="column is-half">
          <form method="post">
            {%  csrf_token %}
            <div class="field">
              <label class="label">Name</label>
              <div class="control">
                <input name="name" class="input" type="text" placeholder="Enter your name">
              </div>
            </div>
            <div class="field">
              <label class="label">Email</label>
              <div class="control">
                <input name="email" class="input" type="email" placeholder="Enter your email if you'd like me to respond">
              </div>
            </div>
            <div class="field">
              <label class="label">Message</label>
              <div class="control">
                <textarea name="message" class="textarea" placeholder="Enter your message"></textarea>
              </div>
            </div>
              <div class="field">
                  <label class="label">Captcha</label>
                  <div class="control">
                      <div class="columns">
                          <div class="column is-2">
                              <img src="{{ captcha_img_url }}" alt="Captcha">
                          </div>
                          <div class="column is-10">
                              <input name="captcha_1" class="input" placeholder="Enter captcha">
                              <input name="captcha_0" type="hidden" value="{{ captcha_key }}">
                          </div>
                  </div>
              </div>
            <div class="field">
              <div class="control">
                <button type="submit" class="button is-primary">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>AussieShopper</strong> by <a href="http://codedemigod.com">Alaa Salman</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
                                       is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC
                                                                                                               SA
                                                                                                               4.0</a>.
      </p>
    </div>
  </footer>
{% endblock %}

web/templates/web/statistics.html
{% extends 'web/base.html' %}
{% load render_bundle from webpack_loader %}

{% block title %}Statistics{% endblock %}

{% block extrajs %}
  {% render_bundle 'main' %}
{% endblock %}

{% block content %}
  <section class="section">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Total Deals</p>
          <p class="title">{{ total_deals }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Total Messages Handled</p>
          <p class="title">{{ total_messages }}</p>
        </div>
      </div>
    </nav>
  </section>
  <section class="section">
    <div class="columns is-centered">
      <div class="column is-half">
      <div id="statscontainer"></div>
      </div>
    </div>
  </section>
{% endblock %}